version: '3.6'
services:
  postgres:
    image: postgres
    # image: postgres:10-alpine
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    # To set password, use, etc. Default is u/p/db: postgres/none/postgres
    environment:
      POSTGRES_DB: warthog-example
      POSTGRES_PASSWORD: testpassword
      POSTGRES_USER: postgres

  admin:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080

volumes:
  db_data:
